### ISSUE TITLE
CI: Implement CodeSpell 

### ISSUE THREAD

**Issue by pcaversaccio** [pcaversaccio/create2deployer#72]
Implement CodeSpell in the CI: https://github.com/codespell-project/actions-codespell: 

```yml
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@v1.0
        with:
          check_filenames: true
          skip: yarn.lock
```
